
-- filtering data

-- Where – filter rows based on a specified condition.
-- AND operator – combine two boolean expressions and return true if both expressions evaluate to true.
-- OR operator – combine two boolean expressions and return false if either expression evaluates to false.
-- Limit – retrieve a subset of rows generated by a query.
-- Fetch– limit the number of rows returned by a query.
-- In – select data that matches any value in a list of values.
-- Between – select data that is a range of values.
-- Like – filter data based on pattern matching.
-- Is Null – check if a value is null or not.

-- WHERE filter

-- syntax
SELECT column1, column2, ...
FROM table_name
WHERE condition1 AND|OR condition2 ...;
-- example
SELECT first_name, last_name
FROM customers
WHERE customer_id = 1 AND country = 'USA';

-- AND operator
-- syntax
SELECT column1, column2, ...
FROM table_name
WHERE condition1 AND condition2 ...;
-- example
SELECT first_name, last_name
FROM customers
WHERE country = 'USA' AND city = 'New York';

-- OR operator
-- syntax
SELECT column1, column2, ...
FROM table_name
WHERE condition1 OR condition2 ...;
-- example
SELECT first_name, last_name
FROM customers
WHERE country = 'USA' OR city = 'New York';

-- LIMIT operator
-- syntax
SELECT column1, column2, ...
FROM table_name
LIMIT number_of_rows;
-- example
SELECT first_name, last_name
FROM customers
LIMIT 5;

-- FETCH operator
-- syntax
SELECT column1, column2, ...
FROM table_name
FETCH FIRST number_of_rows ROWS ONLY;
-- example
SELECT first_name, last_name
FROM customers
FETCH FIRST 5 ROWS ONLY;

-- IN operator
-- syntax
SELECT column1, column2, ...
FROM table_name
WHERE column_name IN (value1, value2, ...);
-- example
SELECT first_name, last_name
FROM customers
WHERE country IN ('USA', 'Canada', 'Mexico');

-- BETWEEN operator
-- syntax   
SELECT column1, column2, ...
FROM table_name
WHERE column_name BETWEEN value1 AND value2;
-- example
SELECT first_name, last_name
FROM customers
WHERE customer_id BETWEEN 1 AND 10;

-- LIKE operator
-- syntax
SELECT column1, column2, ...
FROM table_name
WHERE column_name LIKE pattern;
-- example
SELECT first_name, last_name
FROM customers
WHERE first_name LIKE 'A%';

-- IS NULL operator
-- syntax
SELECT column1, column2, ...
FROM table_name
WHERE column_name IS NULL;
-- example
SELECT first_name, last_name
FROM customers
WHERE email IS NULL;